// codegen generates Zod v4 schemas from codersdk Go types via guts.
//
// Usage: make gen
//
// The output replaces hand-maintained API schemas. Action-specific
// schemas (inputs, outputs) remain hand-written in schemas.ts.
package main

import (
	"fmt"
	"log"
	"maps"
	"os"
	"slices"
	"strings"

	"github.com/coder/guts"
	"github.com/coder/guts/bindings"
	"github.com/coder/guts/config"
)

// Types the action needs from the Coder API. Only root types that
// are not pulled transitively belong here. Everything else is
// excluded to keep the generated file small and the bundle lean.
var wantedTypes = map[string]bool{
	"Chat":                     true,
	"CreateChatMessageRequest": true,
	"CreateChatRequest":        true,
	"Organization":             true,
	"User":                     true,
}

func main() {
	gen, err := guts.NewGolangParser()
	if err != nil {
		log.Fatalf("new parser: %v", err)
	}

	err = gen.IncludeGenerate("github.com/coder/coder/v2/codersdk")
	if err != nil {
		log.Fatalf("include generate: %v", err)
	}

	gen.IncludeCustomDeclaration(config.StandardMappings())
	gen.IncludeCustomDeclaration(map[string]guts.TypeOverride{
		"encoding/json.RawMessage": func() bindings.ExpressionType {
			kw := bindings.KeywordUnknown
			return &kw
		},
		// ChatMessagePart uses a discriminated union in Go (via
		// `variants` struct tags) that guts flattens into a single
		// object with all fields required. The API returns
		// part-type-specific subsets, so strict validation fails.
		// The action never inspects message parts directly.
		"github.com/coder/coder/v2/codersdk.ChatMessagePart": func() bindings.ExpressionType {
			kw := bindings.KeywordUnknown
			return &kw
		},
	})

	ts, err := gen.ToTypescript()
	if err != nil {
		log.Fatalf("to typescript: %v", err)
	}

	ts.ApplyMutations(
		config.EnumAsTypes,
		config.SimplifyOmitEmpty,
	)

	// Collect all nodes then filter to wanted types plus any
	// types they reference that are also in the full set.
	allNodes := make(map[string]bindings.Node)
	ts.ForEach(func(name string, node bindings.Node) {
		allNodes[name] = node
	})

	// Resolve transitive references so we don't emit broken
	// schema references.
	included := resolveTransitive(allNodes, wantedTypes)

	// Topological sort: emit dependencies before dependents.
	names := topoSort(included)

	var b strings.Builder
	b.WriteString("// Code generated by 'make gen'. DO NOT EDIT.\n")
	b.WriteString("import { z } from \"zod\";\n\n")

	for _, name := range names {
		s := serializeNode(name, included[name])
		if s != "" {
			b.WriteString(s)
			b.WriteString("\n")
		}
	}

	_, _ = fmt.Fprint(os.Stdout, b.String())
}

// resolveTransitive starts from the seeds and pulls in any
// referenced types that exist in allNodes.
func resolveTransitive(allNodes map[string]bindings.Node, seeds map[string]bool) map[string]bindings.Node {
	result := make(map[string]bindings.Node)
	var visit func(name string)
	visit = func(name string) {
		if _, ok := result[name]; ok {
			return
		}
		node, exists := allNodes[name]
		if !exists {
			return
		}
		result[name] = node
		for _, ref := range collectRefs(node) {
			visit(ref)
		}
	}
	for name := range seeds {
		visit(name)
	}
	return result
}

// collectRefs extracts all type reference names from a node.
func collectRefs(node bindings.Node) []string {
	var refs []string
	var walkExpr func(bindings.ExpressionType)
	walkExpr = func(expr bindings.ExpressionType) {
		if expr == nil {
			return
		}
		switch e := expr.(type) {
		case *bindings.ReferenceType:
			refs = append(refs, e.Name.Ref())
			for _, arg := range e.Arguments {
				walkExpr(arg)
			}
		case *bindings.ArrayType:
			walkExpr(e.Node)
		case *bindings.ArrayLiteralType:
			for _, el := range e.Elements {
				walkExpr(el)
			}
		case *bindings.UnionType:
			for _, t := range e.Types {
				walkExpr(t)
			}
		case *bindings.TypeLiteralNode:
			for _, m := range e.Members {
				walkExpr(m.Type)
			}
		case *bindings.TypeIntersection:
			for _, t := range e.Types {
				walkExpr(t)
			}
		case *bindings.ExpressionWithTypeArguments:
			walkExpr(e.Expression)
			for _, arg := range e.Arguments {
				walkExpr(arg)
			}
		case *bindings.OperatorNodeType:
			walkExpr(e.Type)
		case *bindings.TupleType:
			walkExpr(e.Node)
		}
	}
	switch n := node.(type) {
	case *bindings.Interface:
		for _, f := range n.Fields {
			walkExpr(f.Type)
		}
		for _, h := range n.Heritage {
			for _, arg := range h.Args {
				walkExpr(arg)
			}
		}
	case *bindings.Alias:
		walkExpr(n.Type)
	}
	return refs
}

// topoSort returns names in dependency order (dependencies first).
// Ties within the same depth level are broken alphabetically.
func topoSort(nodes map[string]bindings.Node) []string {
	visited := make(map[string]bool)
	var order []string

	var visit func(string)
	visit = func(name string) {
		if visited[name] {
			return
		}
		visited[name] = true
		node, ok := nodes[name]
		if !ok {
			return
		}
		// Visit dependencies first.
		deps := collectRefs(node)
		slices.Sort(deps)
		for _, dep := range deps {
			if _, exists := nodes[dep]; exists {
				visit(dep)
			}
		}
		order = append(order, name)
	}

	// Start visits in alphabetical order for stable output.
	for _, name := range slices.Sorted(maps.Keys(nodes)) {
		visit(name)
	}
	return order
}
