// Code generated by 'make gen'. DO NOT EDIT.
import { z } from "zod";

export const ChatClientTypeSchema = z.enum(["api", "ui"]);
export type ChatClientType = z.infer<typeof ChatClientTypeSchema>;

export const ChatDiffStatusSchema = z.object({
	chat_id: z.string(),
	url: z.string().optional(),
	pull_request_state: z.string().optional(),
	pull_request_title: z.string(),
	pull_request_draft: z.boolean(),
	changes_requested: z.boolean(),
	additions: z.number(),
	deletions: z.number(),
	changed_files: z.number(),
	author_login: z.string().optional(),
	author_avatar_url: z.string().optional(),
	base_branch: z.string().optional(),
	head_branch: z.string().optional(),
	pr_number: z.number().optional(),
	commits: z.number().optional(),
	approved: z.boolean().optional(),
	reviewer_count: z.number().optional(),
	refreshed_at: z.string().optional(),
	stale_at: z.string().optional(),
});
export type ChatDiffStatus = z.infer<typeof ChatDiffStatusSchema>;

export const ChatErrorKindSchema = z.enum([
	"auth",
	"config",
	"generic",
	"overloaded",
	"rate_limit",
	"startup_timeout",
	"timeout",
	"usage_limit",
]);
export type ChatErrorKind = z.infer<typeof ChatErrorKindSchema>;

export const ChatErrorSchema = z.object({
	message: z.string(),
	detail: z.string().optional(),
	kind: ChatErrorKindSchema.optional(),
	provider: z.string().optional(),
	retryable: z.boolean(),
	status_code: z.number().optional(),
});
export type ChatError = z.infer<typeof ChatErrorSchema>;

export const ChatFileMetadataSchema = z.object({
	id: z.string(),
	owner_id: z.string(),
	organization_id: z.string(),
	name: z.string(),
	mime_type: z.string(),
	created_at: z.string(),
});
export type ChatFileMetadata = z.infer<typeof ChatFileMetadataSchema>;

export const ChatPlanModeSchema = z.enum(["plan"]);
export type ChatPlanMode = z.infer<typeof ChatPlanModeSchema>;

export const ChatStatusSchema = z.enum([
	"completed",
	"error",
	"paused",
	"pending",
	"requires_action",
	"running",
	"waiting",
]);
export type ChatStatus = z.infer<typeof ChatStatusSchema>;

export const ChatSchema = z.object({
	id: z.string(),
	organization_id: z.string(),
	owner_id: z.string(),
	owner_username: z.string().optional(),
	owner_name: z.string().optional(),
	workspace_id: z.string().optional(),
	build_id: z.string().optional(),
	agent_id: z.string().optional(),
	parent_chat_id: z.string().optional(),
	root_chat_id: z.string().optional(),
	last_model_config_id: z.string(),
	title: z.string(),
	status: ChatStatusSchema,
	plan_mode: ChatPlanModeSchema.optional(),
	last_error: ChatErrorSchema.optional(),
	last_turn_summary: z.string().nullable(),
	diff_status: ChatDiffStatusSchema.optional(),
	created_at: z.string(),
	updated_at: z.string(),
	archived: z.boolean(),
	pin_order: z.number(),
	mcp_server_ids: z.array(z.string()),
	labels: z.record(z.string(), z.string()).nullable(),
	files: z.array(ChatFileMetadataSchema).optional(),
	has_unread: z.boolean(),
	last_injected_context: z.array(z.unknown()).optional(),
	warnings: z.array(z.string()).optional(),
	client_type: ChatClientTypeSchema,
	children: z.array(z.lazy((): z.ZodType => ChatSchema)),
});
export type Chat = z.infer<typeof ChatSchema>;

export const ChatBusyBehaviorSchema = z.enum(["interrupt", "queue"]);
export type ChatBusyBehavior = z.infer<typeof ChatBusyBehaviorSchema>;

export const ChatInputPartTypeSchema = z.enum([
	"file",
	"file-reference",
	"text",
]);
export type ChatInputPartType = z.infer<typeof ChatInputPartTypeSchema>;

export const ChatInputPartSchema = z.object({
	type: ChatInputPartTypeSchema,
	text: z.string().optional(),
	file_id: z.string().optional(),
	file_name: z.string().optional(),
	start_line: z.number().optional(),
	end_line: z.number().optional(),
	content: z.string().optional(),
});
export type ChatInputPart = z.infer<typeof ChatInputPartSchema>;

export const CreateChatMessageRequestSchema = z.object({
	content: z.array(ChatInputPartSchema),
	model_config_id: z.string().optional(),
	mcp_server_ids: z.array(z.string()).optional(),
	busy_behavior: ChatBusyBehaviorSchema.optional(),
	plan_mode: ChatPlanModeSchema.optional(),
});
export type CreateChatMessageRequest = z.infer<
	typeof CreateChatMessageRequestSchema
>;

export const DynamicToolSchema = z.object({
	name: z.string(),
	description: z.string().optional(),
	input_schema: z.unknown(),
});
export type DynamicTool = z.infer<typeof DynamicToolSchema>;

export const CreateChatRequestSchema = z.object({
	organization_id: z.string(),
	content: z.array(ChatInputPartSchema),
	system_prompt: z.string().optional(),
	workspace_id: z.string().optional(),
	model_config_id: z.string().optional(),
	mcp_server_ids: z.array(z.string()).optional(),
	labels: z.record(z.string(), z.string()).optional(),
	unsafe_dynamic_tools: z.array(DynamicToolSchema).optional(),
	plan_mode: ChatPlanModeSchema.optional(),
	client_type: ChatClientTypeSchema.optional(),
});
export type CreateChatRequest = z.infer<typeof CreateChatRequestSchema>;

export const LoginTypeSchema = z.enum([
	"github",
	"none",
	"oidc",
	"password",
	"token",
	"",
]);
export type LoginType = z.infer<typeof LoginTypeSchema>;

export const MinimalOrganizationSchema = z.object({
	id: z.string(),
	name: z.string(),
	display_name: z.string(),
	icon: z.string(),
});
export type MinimalOrganization = z.infer<typeof MinimalOrganizationSchema>;

export const MinimalUserSchema = z.object({
	id: z.string(),
	username: z.string(),
	name: z.string().optional(),
	avatar_url: z.string().optional(),
});
export type MinimalUser = z.infer<typeof MinimalUserSchema>;

export const OrganizationSchema = MinimalOrganizationSchema.extend({
	description: z.string(),
	created_at: z.string(),
	updated_at: z.string(),
	is_default: z.boolean(),
});
export type Organization = z.infer<typeof OrganizationSchema>;

export const UserStatusSchema = z.enum(["active", "dormant", "suspended"]);
export type UserStatus = z.infer<typeof UserStatusSchema>;

export const ReducedUserSchema = MinimalUserSchema.extend({
	email: z.string(),
	created_at: z.string(),
	updated_at: z.string(),
	last_seen_at: z.string().optional(),
	status: UserStatusSchema,
	login_type: LoginTypeSchema,
	is_service_account: z.boolean().optional(),
	theme_preference: z.string().optional(),
});
export type ReducedUser = z.infer<typeof ReducedUserSchema>;

export const SlimRoleSchema = z.object({
	name: z.string(),
	display_name: z.string(),
	organization_id: z.string().optional(),
});
export type SlimRole = z.infer<typeof SlimRoleSchema>;

export const UserSchema = ReducedUserSchema.extend({
	organization_ids: z.array(z.string()),
	roles: z.array(SlimRoleSchema),
	has_ai_seat: z.boolean(),
});
export type User = z.infer<typeof UserSchema>;
